### ISSUE TITLE
Not compatible with libgit2 version 0.25

### ISSUE THREAD

**Issue by Neo-Oli** [hendotcat/ppl#63]
`libgit2 version is not compatible, expected ~> 0.24.0`

**Comment by hendotcat** [comment]
Hey I'm gonna close this cos it's 4 years old (sorry lol, been a very busy 4 years). If whatever this is still causes trouble for anyone, please feel free to re-open this issue or make a new one about it. Might need a teeny tiny bit of extra info about e.g. the operating system and what command is producing this error message though next time!

**Comment by Neo-Oli** [comment]
@hendotcat That's fine. I don't remember anything about this issue anymore, except it somehow not working for me and then I just wrote [my own thing](https://github.com/Neo-Oli/contact) for contact management.

**Comment by hendotcat** [comment]
Oh **fuck yeah** that thing is SO cool! Love how simple the design is: I've often felt that ppl turned out a liiiiiittle bit overengineered (wrote it during a phase where I was learning TDD etc and took some things a bit far) and your app has the exact opposite approach which means you can read + understand the whole thing in 5 minutes! Happy to learn it exists so thanks for posting the link! ❤️
