### ISSUE TITLE
Add support for the RELATED field

### ISSUE THREAD

**Issue by acant** [hendotcat/ppl#70]
The vcard [RELATED](https://tools.ietf.org/html/rfc6350#section-6.6.6) will allow cards to be connected to each other and their relationships described.

The conversion to the vcard gem should be done first, #68, then support for this field can be added to vcard and ppl.

(This issue was originally discussed in #67 )

**Comment by hendotcat** [comment]
Anything that turns a bunch of data into a graph is always cool in my book. I'd love having a `ppl related` command or whatever it'd be called! Since it hasn't gotten built after all this time I'm gonna assume it's probably not gonna get built and close this. But leaving this note behind juuuuust in case there's some interested person browsing the issue archive for inspiration.

You there! Unknown future interested person ! Build us this idea and send a pull request!
