### ISSUE TITLE
Test out using the Thor gem for the CLI

### ISSUE THREAD

**Issue by acant** [hendotcat/ppl#72]
The [thor gem](https://github.com/erikhuda/thor) implements the CLI pattern which is being used:
```
ppl COMMAND arg1 arg2 arg3
```

So it might be possible to eliminate some code, and make it easier for new developers who might already be familiar with thor.

(This issue was originally discussed in #67 )

**Comment by hendotcat** [comment]
Oh yeah the argument parsing code is some of my least favorite in this repo for sure and replacing it with an open source thing would be lovely. Potentially a nice first PR for someone very ambitious but otherwise unlikely to happen I think, as 4 years on, history has now proven that I'm not personally keen on investing a bunch of time in making changes like this to ppl myself!
