### ISSUE TITLE
Not sure if Ruby version checking is doing the intended thing

### ISSUE THREAD

**Issue by tomr-stargazer** [hendotcat/ppl#83]
Hi! Excited to use ppl.

It looks like I had to specify the current version in order to install ppl. Is the following the intended behavior when a version is not specified in gem install?

```
(base) ➜  ~ sudo gem install ppl
ERROR:  Error installing ppl:
	The last version of ppl (>= 0) to support your Ruby & RubyGems was 3.0.1. Try installing it with `gem install ppl -v 3.0.1`
	ppl requires Ruby version >= 3.0.0. The current ruby version is 2.6.3.62.
(base) ➜  ~ which ruby
/usr/bin/ruby
(base) ➜  ~ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
(base) ➜  ~ sudo gem install ppl -v 3.0.1
Fetching mime-types-1.25.1.gem
[...] # abridged by me for clarity
Fetching ppl-3.0.1.gem
Building native extensions. This could take a while...
[...] # abridged by me for clarity
Done installing documentation for rugged, polyglot, treetop, mime-types, mail, inifile, ppl after 7 seconds
7 gems installed
```

**Comment by hendotcat** [comment]
Ah hey there! Yeah I did some maintenance work on ppl recently and bumped the minimum required Ruby version to 3.0.0 so that's why you're getting that error: your version of Ruby is quite old and I guess that's the gem install UX that results.

The reason for requiring the very latest major Ruby version is simple: my time's really precious and maintaining support for multiple Ruby versions in ppl is not a way I wanna spend it! There were some horrifying backwards-incompatible UTF8-related changes during the Ruby v2 era which wasted an absolute tonne of my time, and so a policy of only supporting the very latest Ruby version is a tidy way of drawing a line under that 😇

**Comment by tomr-stargazer** [comment]
Thanks @hendotcat for answering my Q! (:
