### ISSUE TITLE
Undo "ppl init"

### ISSUE THREAD

**Issue by tomr-stargazer** [hendotcat/ppl#84]
I accidentally ran "ppl init" in a directory that I did not intend to turn into a git directory (namely, my ~/Documents folder). I believe that the correct course of action here is just to remove the .git folder, but I'm not sure this will be clear to less git-savvy users — so I wanted to flag this in case you're interested in updating the docs (or adding a new command) for deleting a ppl "repository".

(Also! I found ppl via HN today: [link](https://news.ycombinator.com/item?id=27440516). Nice work.)

**Comment by hendotcat** [comment]
Oh interesting! This is a good point about the onboarding UX. Maybe instead of an undo command, it might be simpler to detect if the init command's target directory is empty before proceeding. I guess there are probably cases where you might want to deliberately initialise an address book in a non-empty directory too, so maybe a y/n confirmation prompt could be the way to go. What do you think?

**Comment by hendotcat** [comment]
If somebody feels like tweaking the `ppl init` behaviour in the way I was describing in the last comment, it could make for a pretty helpful PR that improves the onboarding UX slightly! I'm gonna close this issue in the meantime though because I don't want to send the wrong signals about how likely I am to do this work myself: I'm incredibly busy most of the time, and apart from some basic "keeping the lights on" maintenance I'm not keen to do a bunch of new development work on ppl myself right now! 😄

**Comment by tomr-stargazer** [comment]
That sounds good @hendotcat  - thanks for your response!
