### ISSUE TITLE
create brew install

### ISSUE THREAD

**Issue by kriss9** [hendotcat/ppl#85]
just saw this on hacker news. would be great to have easy brew install from moment of engagement (i.e. love at first site).

**Comment by hendotcat** [comment]
Hell yeah! I would absolutely _love_ to change the setup instructions for ppl to `brew install ppladdressbook` or something like that. Unfortunately though, I have no idea how to set that up and no time available to figure it out :(

If you know how or can figure out how to do it, and you have the time, I'd welcome a pull request! Although maybe it's actually a pull request for the homebrew repository rather than this one? I have literally no idea TBQH! In the meantime this one's unfortunately a no, sorry!
