### ISSUE TITLE
Mac/iOS integration

### ISSUE THREAD

**Issue by kriss9** [hendotcat/ppl#86]
CLI tools are good at basic sorts (e.g. `ls -` commands). Most address books do not offer this by default (i.e. Mac OS). This item is to A) integrate with Mac OS X/Address book out of the box and B) make an easy sort by date (if not already existing) [likely a separate issue].

Again, cool project!

**Comment by hendotcat** [comment]
Hey! I think there might be some pretty good CLI address book apps out there that focus on integrating nicely with apps like those. I'm not sure though: the landscape has changed a lot in this cosy little product space since I last did anything resembling proper market research. I don't know how I'd even begin to add something like that to ppl though to be honest. It sounds bloody hard and I'm a bit short of time to throw at ideas like those unfortunately! Could be a fun idea to play around with for someone with some time on their hands and a lot of optimism in their heart though! In the meantime I'm gonna close the issue, just so I don't send the wrong signal to the community about whether or not this is being currently worked on 😄
