### ISSUE TITLE
Windows OS Support

### ISSUE THREAD

**Issue by graphixillusion** [hendotcat/ppl#87]
Hi there. As the title says: is it possible to add Windows OS support? I've already tried to build it with msys, i got everything compiled but at the end it doesn't work. Thank you!

**Comment by hendotcat** [comment]
Hey! Oof, this is a tough one! I feel super grateful to find out that there's demand for something like this, but unfortunately it's impossible for me to deliver. I don't have any of the hardware or licenses I'd need in order to be able to build & test a Windows version of ppl. Even if I did, I don't think I'd have the time for it either :(

However!!! If someone managed to figure out how to fix ppl's Windows compatibility and sent a pull request, I could probably find the time to review that! Until then, I'm afraid this one has to be a no though. Sorry!
